# Creating NumPy Array
## Example: 1D- NumPy Array

In [1]:
import numpy as np
a = np.array([3, -1, 0, 2.1])
print('a = ',a)
print ('Type = ', type(a))
print('Data Type = ', a.dtype)


a =  [ 3.  -1.   0.   2.1]
Type =  <class 'numpy.ndarray'>
Data Type =  float64


## Example: 2D- NumPy Array


In [2]:
import numpy as np
b = np.array([[3, -1, 0],[1, 3, -6]])
print('b = ',b)
print('')
print ('Type = ', type(b))
print('Data Type = ', b.dtype)
print('Shape = ', b.shape)


b =  [[ 3 -1  0]
 [ 1  3 -6]]

Type =  <class 'numpy.ndarray'>
Data Type =  int32
Shape =  (2, 3)


##  Example: Using Built-in Functions to Create   1-D and 2-D array 


In [3]:
import numpy as np

# Generates 1-D array from 0 t0 10(exclude) with step size 0.5
a = np.arange(0, 10, 0.5) 
print('a = ', a)

# Generates 1-D array with 10 points equally spaced on the interval [-1,1]
b = np.linspace(-1,1,10) 
print('b = ', b)

# 3x2 zero matrix
c = np.zeros((3, 2)) 
print('c = ', c)

# 2x3 matrix of 1's
d = np.ones((2, 3)) 
print('d = ', d)

# 3x3 identity matrix
I = np.eye(3) 
print('I = ', I)


a =  [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
b =  [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]
c =  [[0. 0.]
 [0. 0.]
 [0. 0.]]
d =  [[1. 1. 1.]
 [1. 1. 1.]]
I =  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Example: Mean, standard deviation, variance of 1D-Array

In [4]:
import numpy as np
a = np.array([2.5, 3.5, 3.1, 4.0, 3.8, 2.5, 3.5, 3.7, 3.8, 3.9, 2.0,3.0, 2.3, 3.2, 4.0, 1.5,]) # Array of class grade
mean = a.mean()
print('Mean = ', mean)
Var = a.var()
print('Variance = ', Var)
Std = a.std()
print('Standard Deviation = ',Std)

Mean =  3.14375
Variance =  0.5649609375
Standard Deviation =  0.7516388344810292


## Example: Indexing the 1-D Array

In [5]:
import numpy as np
x = np.array([3, -2, 5, 0, 7]) 
print('x[0] = ',x[0])
print('x[1] = ',x[1])
print('x[2] = ',x[2])
print('x[3] = ',x[3])
print('x[4] = ',x[4])
print('x[-1] = ',x[1])
print('x[-3] = ',x[-3])

x[0] =  3
x[1] =  -2
x[2] =  5
x[3] =  0
x[4] =  7
x[-1] =  -2
x[-3] =  5


## Example: Slicing the 1-D Array

In [6]:
import numpy as np
x = np.array([3, -2, 5, 0, 7])
print('x[:] = ', x[:])
print('x[0:] = ', x[0:])
print('x[0:4] = ', x[0:4])
print('x[0:5] = ', x[0:5])
print('x[0:-1] = ', x[0:-1])
print('x[2:] = ', x[2:])
print('x[1:4] = ', x[1:4])

x[:] =  [ 3 -2  5  0  7]
x[0:] =  [ 3 -2  5  0  7]
x[0:4] =  [ 3 -2  5  0]
x[0:5] =  [ 3 -2  5  0  7]
x[0:-1] =  [ 3 -2  5  0]
x[2:] =  [5 0 7]
x[1:4] =  [-2  5  0]


## Example: Updating the 1-D Array

In [7]:
x = np.array([3, -2, 5, 0, 7])
print('x = ', x)
x[0] = 4
print('x = ', x)
x[-1] = -5
print('x = ', x)

x =  [ 3 -2  5  0  7]
x =  [ 4 -2  5  0  7]
x =  [ 4 -2  5  0 -5]


## Example: Indexing the 2-D Array

In [8]:
import numpy as np
x = np.array([[1,0,3,-2],[2,1,0,7],[2,-3,1,4]])
print('x = ',x)
print('x[0,0] = ',x[0,0])
print('x[1,1] = ',x[1,2])
print('x[-1,-1] = ',x[-1,-1])
print('x[-2,1] = ',x[-2,-1])



x =  [[ 1  0  3 -2]
 [ 2  1  0  7]
 [ 2 -3  1  4]]
x[0,0] =  1
x[1,1] =  0
x[-1,-1] =  4
x[-2,1] =  7


## Example: Slicing the 2-D Array

In [9]:
import numpy as np
x = np.array([[1,0,3,-2],[2,1,0,7],[2,-3,1,4]])
print('x = ',x)
print('x[:,0] = ', x[:,0])
print('x[1,:] = ', x[1,:])
print('x[1:3,2:4] = ', x[1:3,2:4])


x =  [[ 1  0  3 -2]
 [ 2  1  0  7]
 [ 2 -3  1  4]]
x[:,0] =  [1 2 2]
x[1,:] =  [2 1 0 7]
x[1:3,2:4] =  [[0 7]
 [1 4]]


## Example: Updating the 2-D Array

In [10]:
import numpy as np
x = np.array([[1,0,3,-2],[2,1,0,7],[2,-3,1,4]])
print('x = ',x)
x[0,0] = 4
x[-1,-1] = -1
print('x = ',x)

x =  [[ 1  0  3 -2]
 [ 2  1  0  7]
 [ 2 -3  1  4]]
x =  [[ 4  0  3 -2]
 [ 2  1  0  7]
 [ 2 -3  1 -1]]


## Example: Arithmetic Operations on 1-D Array


In [11]:
import numpy as np
x = np.array([1,0,3,-2])
y = np.array([-2,1,2,3])
z1 = x + y
z2 = x*y
z3 = x/y
print('x+y = ', z1)
print('x*y = ', z2)
print('x/y = ', z3)

x+y =  [-1  1  5  1]
x*y =  [-2  0  6 -6]
x/y =  [-0.5         0.          1.5        -0.66666667]


## Example: Arithmetic Operations on 2-D Array

In [12]:
import numpy as np
A = np.array([[1,0,3],[2,1,4],[2,1,5]])
B = np.array([[-2,1,2],[5,3,-1],[2,3,2]])
C1 = A + B
C2 = A * B
C3 = A / B
C4 = A % B
print('A+B = ', C1)
print('A*B = ', C2)
print('A/B = ', C3)
print('A%B = ', C4)




A+B =  [[-1  1  5]
 [ 7  4  3]
 [ 4  4  7]]
A*B =  [[-2  0  6]
 [10  3 -4]
 [ 4  3 10]]
A/B =  [[-0.5         0.          1.5       ]
 [ 0.4         0.33333333 -4.        ]
 [ 1.          0.33333333  2.5       ]]
A%B =  [[-1  0  1]
 [ 2  1  0]
 [ 0  1  1]]


## Example: Scalar $\alpha$ Arithmetic Operations with Array $A$
## $\alpha + A$, $\alpha*A$, $A/\alpha$

In [13]:
import numpy as np
A = np.array([[1,0,3],[2,1,4],[2,1,5]])
alpha = 2
print('A = ', A)
print('alpha+A = ', alpha + A)
print('alpha*A = ', alpha*A)
print('A/alpha = ', A/alpha)

A =  [[1 0 3]
 [2 1 4]
 [2 1 5]]
alpha+A =  [[3 2 5]
 [4 3 6]
 [4 3 7]]
alpha*A =  [[ 2  0  6]
 [ 4  2  8]
 [ 4  2 10]]
A/alpha =  [[0.5 0.  1.5]
 [1.  0.5 2. ]
 [1.  0.5 2.5]]


# NumPy Linear Algebra
## Scalar product


In [14]:

import numpy as np
a = np.array([3,1,2])
b = np.array([-2,3,-2])
c = np.dot(a,b)
print(c)

-7


## Vector product

In [15]:
#import numpy as np
a = np.array([3,1,2])
b = np.array([-2,3,-2])
c = np.cross(a,b)
print(c)

[-8  2 11]


## Matrix Multiplication

In [16]:
#import numpy as np
A = np.array([[3,1,2],[-1,2,5]])
B = np.array([[-2,3,-2],[0,1,3],[2,1,-4]])
C= np.matmul(A,B)
print(C)


[[ -2  12 -11]
 [ 12   4 -12]]


## Matrix Multiplication (Another way)
### Converting array into matrix

In [17]:
#import numpy as np
A = np.array([[3,1,2],[-1,2,5]])
B = np.array([[-2,3,-2],[0,1,3],[2,1,-4]])
A = np.matrix(A)
B = np.matrix(B)
C= A*B
print(C)

[[ -2  12 -11]
 [ 12   4 -12]]


## Determinant of a Matrix

In [18]:
import numpy as np
A = np.array([[-2,3,-2],[0,1,3],[2,1,-4]])
Det = np.linalg.det(A)


## Inverse of a Matrix

In [19]:
#import numpy as np
A = np.array([[-2,3,-2],[0,1,3],[2,1,-4]])
A_inv = np.linalg.inv(A)
print(A_inv)

[[-0.19444444  0.27777778  0.30555556]
 [ 0.16666667  0.33333333  0.16666667]
 [-0.05555556  0.22222222 -0.05555556]]


## Solve a System of Linear Equations
### $$2x+4y+2z=16\\-2x-3y+z=-5\\2x+2y-3z=-3$$

In [20]:
#import numpy as np
A = np.array([[2,4,2],[-2,-3,1],[2,2,-3]])
b = np.array([16,-5,-3])
X = np.linalg.solve(A,b)
print(X)

[1. 2. 3.]


# Random Numbers in NumPy

## Example: Uniformaly distributed random number on [0,1] of size mxn
### Syntax: np.ranom.rand(m,n)


In [21]:
import numpy as np
R1  = np.random.rand(3)
R2  = np.random.rand(1,3)
R3  = np.random.rand(3,2)
print('R1 = ', R1)
print('R2 = ', R2)
print('R3 = ', R3)

R1 =  [0.06605519 0.20574304 0.92036353]
R2 =  [[0.59029482 0.04830864 0.66846596]]
R3 =  [[0.79312227 0.91509326]
 [0.25801221 0.684437  ]
 [0.85428208 0.93240939]]


## Example: Standard normal ly  distributed random number of size mxn
### Syntax: np.ranom.randn(m,n)

In [22]:
import numpy as np
R1  = np.random.randn(3)
R2  = np.random.randn(1,3)
R3  = np.random.randn(3,2)
print('R1 = ', R1)
print('R2 = ', R2)
print('R3 = ', R3)

R1 =  [0.70572368 0.41323827 0.06883548]
R2 =  [[-0.67432006 -0.20310805 -0.175312  ]]
R3 =  [[-2.02277104 -0.01135208]
 [ 0.81524839 -0.97210814]
 [ 0.105472    0.45644087]]


## Example: Random intergers from low L to high H (exclusive) of given size mxn
### Syntax: np.ranom.randint(L,H,(m,n))

In [23]:
import numpy as np
R1  = np.random.randint(0,10,5)
R2  = np.random.randint(0,10,(1,5))
R3  = np.random.randint(2,10,(4,3))
print('R1 = ', R1)
print('R2 = ', R2)
print('R3 = ', R3)


R1 =  [9 2 5 8 0]
R2 =  [[5 5 4 1 2]]
R3 =  [[8 9 7]
 [7 4 4]
 [9 6 5]
 [3 3 6]]
